apiVersion: v1
kind: Pod
metadata:
  name: init-container
spec:
  volumes:
    - name: cache-volume
      emptyDir: {}
  initContainers:
    - name: init-container
      image: busybox
      command: ["/bin/sh", "-c", "echo 'hello Kubernetes!' > /workdir/index.html"]
      volumeMounts:
        - mountPath: /workdir
          name: cache-volume
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: cache-volume
